# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-04 12:50
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20200804_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='picture',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]